# -*- mode: ruby -*-
# vi: set ft=ruby :

$BASE_BOX = 'ubuntu/trusty64'

Vagrant.configure(2) do |config|
	config.vm.provider 'virtualbox' do |vb|
		vb.customize ["modifyvm", :id, "--memory", "4096"]
		#vb.gui = false
		#vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
		#vb.customize [ "modifyvm", :id, "--uart1", "off" ]
		#vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]
    	#vb.customize [ "modifyvm", :id, "--uartmode1", "file", "console.log" ]
	end
	config.vm.box = $BASE_BOX
	config.vm.hostname = 'horse-bet'
	config.vm.network 'private_network', type: 'dhcp'
	# Setup directement dans la vagrantbox
	# Attention, la gestion de dépendances est un enfer
	# config.vm.provision 'shell', path: 'provision_horse-bet.sh'
	# setup avec docker
	config.vm.provision 'shell', path: 'provision_docker.sh'
	#config.vm.provision 'shell', path: 'provision_googlechrome.sh'
	#config.vm.provision 'shell', path: 'provision_clean_before_package.sh'
end
